export enum Powers {
  costUp = 'malusCost',
  costDown = 'bonusCost',
  DT = 'DETERMINATION',
  loop = 'loop',
  taunt = 'taunt',
  charge = 'charge',
  haste = 'haste',
  attackUp = 'bonusAtk',
  attackDown = 'malusAtk',
  healthUp = 'bonusHp',
  paralyzed = 'paralyzed',
  candy = 'candy',
  poison = 'poison',
  armor = 'armor',
  dodge = 'dodge',
  burn = 'burn',
  disarmed = 'cantAttack',
  anotherChance = 'anotherChance',
  invulnerable = 'invulnerable',
  transparency = 'transparency',
  silenced = 'silenced',
  caught = 'box',
  shock = 'shock',
  support = 'support',
  bullseye = 'bullseye',
  created = 'created',
}

export default Powers;
